### PR TITLE
use setTimeout.bind

### PR DESCRIPTION
**Pull request by s-a**

### CODE REVIEW

**Comment by jamestalmage** [comment]
Do you have a cross-platform solution? (Node and Browser)?

**Comment by jamestalmage** [comment]
OK, so apparently binding to `null` will work. That's just weird. It shouldn't be that way

**Comment by jamestalmage** [comment]
Well - Chrome does not like this:

```
setTimeout.bind({})(()=> console.log('foo'))
```

weird

**Comment by s-a** [comment]
Sorry I just tried in ironNode.  
I agree `null` does not make sense.  
If this works in Browser only my guess is an electron problem. Are you willing to create an issue there? I have a very bad cold these days :mask: and have to sleep again :/
The creators are highly trained monkeys and the support is very good there. People there know about chrome internals and they can give more professional answers than me. Even if this is not an electron problem. This might be an interesting topic there.

**Comment by jamestalmage** [comment]
This happens in Chrome, even when iron-node is not involved. It's a bug somewhere in V8 / Chrome.

**Comment by s-a** [comment]
Indeed. You found a tricky one :+1: Could you pls reference your iron-node issue (if you are willing to create one) in their ticketsystem so people have a connection and benefit from your work? I guess this is the original repo https://chromium.googlesource.com/v8/v8.git

**Comment by s-a** [comment]
uff.. Cannot find any issue tracker :/

**Comment by jamestalmage** [comment]
I am having the same problem. If you find it, let me know.

**Comment by s-a** [comment]
https://bugs.chromium.org/p/v8/issues/list :laughing:

**Comment by jamestalmage** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=4718

**Comment by jamestalmage** [comment]
thanks for your help!

**Pull request closed without merging**
